// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mglltdkuweeyjzccqguy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nbGx0ZGt1d2VleWp6Y2NxZ3V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NjM1ODksImV4cCI6MjA2NTAzOTU4OX0.2YZEyihG-jEZy8SLnpWp-N65blyWfbM-KHn6vCCdIYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);